[INFO 22:58:08] my_main *******************
[INFO 22:58:08] my_main WANDB RUN ID:
[INFO 22:58:08] my_main ejz9ow0z
[INFO 22:58:08] my_main *******************
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:265: UserWarning: [33mWARN: Human rendering should return `None`, got <class 'bool'>[0m
  logger.warn(
	Done: False
/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/human_play.py:156: UserWarning: Key 65507 not recognized
  warnings.warn(f"Key {k} not recognized")
/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/human_play.py:156: UserWarning: Key 99 not recognized
  warnings.warn(f"Key {k} not recognized")
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/stdout_capturing.py:185: UserWarning: tee_stderr.wait timeout. Forcibly terminating.
  warnings.warn("tee_stderr.wait timeout. Forcibly terminating.")
[DEBUG 22:58:23] pymarl Stopping Heartbeat
[WARNING 22:58:23] pymarl Aborted after 0:00:16!
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 450, in _get_domain
    domain = domain_map[key]
KeyError: (('v2f/dynamic', 't3f/dynamic', 'c4B/dynamic'), 7, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/main.py", line 134, in <module>
    ex.run_commandline(params)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/experiment.py", line 313, in run_commandline
    return self.run(
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/experiment.py", line 277, in run
    run()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/main.py", line 44, in my_main
    run(_run, config, _log)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/run.py", line 67, in run
    run_sequential(args=args, logger=logger)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/run.py", line 138, in run_sequential
    mac = mac_REGISTRY[args.mac](buffer.scheme, groups, args)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/controllers/basic_controller.py", line 50, in __init__
    self.interactive_env = InteractiveRWAREEnv(env="rware-tiny-2ag-v2",
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/human_play.py", line 75, in __init__
    self._cycle()
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/human_play.py", line 186, in _cycle
    self.env.render()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 409, in render
    return super().render()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/core.py", line 332, in render
    return self.env.render()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 303, in render
    return self.env.render()
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/rware/warehouse.py", line 954, in render
    return self.renderer.render(
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/rware/rendering.py", line 128, in render
    self._draw_goals(env)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/robotic_warehouse/rware/rendering.py", line 245, in _draw_goals
    label = pyglet.text.Label(
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/__init__.py", line 473, in __init__
    self.document.set_style(0, len(self.document.text), {
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/document.py", line 596, in set_style
    return super(UnformattedDocument, self).set_style(
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/document.py", line 505, in set_style
    self.dispatch_event('on_style_text', start, end, attributes)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/event.py", line 408, in dispatch_event
    if handler(*args):
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/layout.py", line 1372, in on_style_text
    self._init_document()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/layout.py", line 1336, in _init_document
    self._update()
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/layout.py", line 1260, in _update
    self._create_vertex_lists(left + line.x, top + line.y, line.start, line.boxes, context)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/layout.py", line 1771, in _create_vertex_lists
    box.place(self, i, x, y, context)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/text/layout.py", line 356, in place
    vertex_list = layout.batch.add(n_glyphs * 4, GL_QUADS, group,
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 366, in add
    domain = self._get_domain(False, mode, group, formats)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 456, in _get_domain
    domain = vertexdomain.create_domain(*formats)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 134, in create_domain
    return VertexDomain(attribute_usages)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 183, in __init__
    attribute.buffer = vertexbuffer.create_mappable_buffer(
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 110, in create_mappable_buffer
    return MappableVertexBufferObject(size, target, usage)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 384, in __init__
    super(MappableVertexBufferObject, self).__init__(size, target, usage)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 299, in __init__
    glGenBuffers(1, id)
  File "/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/pyglet/gl/lib.py", line 87, in errcheck
    def errcheck(result, func, arguments):
KeyboardInterrupt
